### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by automaticgiant** [seantis/suitable#10]
so far, super excited about this project. but haven't figured out how to pass environment (proxy) settings through the tunnel to the remote module execution.

**Comment by automaticgiant** [comment]
i hardcoded some env in https://github.com/seantis/suitable/blob/master/suitable/module_runner.py#L100 and it worked, so seems like a good extension point for making proxy stuff work or passing in aws keys or whatever on remote sytems.

**Comment by href** [comment]
Yeah, I just had a look at it and so far this hasn't been implemented. I'll be sure to have a closer look at this next week. Thanks for bringing this up!

**Comment by href** [comment]
I implemented this in the latest version now available on PyPI.

Have a look at the test for a usage example: https://github.com/seantis/suitable/blob/563e46f673012ff7aeacad9ce3a99001be137890/suitable/tests/test_api.py#L215-L220

Basically the environment is set on the api itself. I considered adding it to the commands, but there are modules which use 'environment' as a variable and that would lead to conflicts.

Feel free to reopen if this doesn't solve the issue for you.
