### ISSUE TITLE
Integrate Mitogen into Suitable

### ISSUE THREAD

**Issue by Azulinho** [seantis/suitable#11]
There are some discussions where ansible with the mitogen plugin speeds up things considerably for running playbooks.
My biggest thing about ansible is that as soon things get too complex, the ansible code just becames slow and unmanageable. Mytogen might fix the first bit for non-async playbooks, while it is clear to me that suitable easily solves the second.

I have been using suitable to actually speed up execution of ansible playbooks, by deconstructing them into suitable runs and re-use the common python tooling to manage concurrency, chains , dependencies and so on between runs, saving me minutes over the typically sequentially ran ansible playbooks.

I am now wondering if mitogen and suitable could play along, and get the speed mitogen offers with a pythonic way of doing things with suitable

**Comment by href** [comment]
I'm wondering the exact same thing! - I actually hope to integrate Mitogen into Suitable and maybe even switch to it by default to speed up our Suitable code without touching any of it.

I am however not willing to sacrifice Python 3 compatibility for this, so I'm waiting for Mitogen to achieve that: https://github.com/dw/mitogen/issues/16

Hopefully the kickstarter pans out, so we can get this sooner rather than later :)

Otherwise I have to split the code base and documentation to some degree and I wouldn't be able to eat my own dog food as we have already switched to Python 3.

**Comment by Azulinho** [comment]
sweet

**Comment by dw** [comment]
Just a small update.. the Ansible guys actually supplied the missing piece in the puzzle for gaining 2.x/3.x compat without giving up 2.4, and doing so without 2to3 or having 3.x hosts only able to talk to 3.x hosts :)    Python 3 support is all but guaranteed now, and it's likely a relatively small amount of work, although the truth of that will only become apparent once the tests are in better shape.

**Comment by href** [comment]
> Python 3 support is all but guaranteed now, and it's likely a relatively small amount of work

🍾 awesome!

**Comment by href** [comment]
I think this is happening, so I'm reopening this issue until Mitogen is integrated. I want to make this as easy as possible once I can support all existing Python targets.

For now it already works with Python 2.7 using [the latest commit](https://github.com/seantis/suitable/commit/4ac31552d85ffbfadb3a28a0830c5547fa44a808).

I've created a gist that installs Mitogen and Suitable together and adds a test.py to try it out:
https://gist.github.com/href/efa404837f392d6b84f0b36b59b605a2

Just download the gist and run it as follows:
```bash
bash install.sh mitogen
cd mitogen
bin/python test.py
```

Once mitogen is properly released we should be able to make this process fairly simple. For now we have to manually install the strategy plugin, but I think I can support autoloading in the future, so the install_strategy_plugins step wouldn't be necessary:

```python
from suitable import Api, install_strategy_plugins
install_strategy_plugins('/path/to/mitogen-master/ansible_mitogen/plugins/strategy')

api = Api('localhost', strategy='mitogen_linear')
api.command('whoami')
```

In my tests I see speedups between 2x and 5x, so this looks great 👍

**Comment by dw** [comment]
I'll make room this weekend for a few more hours of python3 work, it really shouldn't require much. Also note for testing, the second and subsequent commands will always be much faster, as the target module cache will have been primed. :)

**Comment by href** [comment]
> Also note for testing, the second and subsequent commands will always be much faster, as the target module cache will have been primed. :)

Thanks, I noticed that. Ansible itself also gains a bit through caching, so I'll have to keep an eye on that. Especially since those caches are bound to each Suitable Api instance. Maybe I can be smarter and share the cache between Api instances, but that means I have to descend into the bowels of Ansible 😨

Either way, the speed up is there on all fronts already :)

**Comment by dw** [comment]
At least the Mitogen parts /should/ be per-process, but I haven't looked there in months :)  Even if you reconstruct all the internal Ansible objects, the connection multiplexer process and all child connections should outlive e.g. the current TaskQueueManager instance, etc.  Thanks for reminding me of this, it's something that must be preserved for the v2 extension design.

**Comment by href** [comment]
> the connection multiplexer process and all child connections should outlive e.g. the current TaskQueueManager instance

That would be great 👍

**Comment by Azulinho** [comment]
this is great, and to show my appreciation I will be sleeping with all of
you.
who is going to be first?

**Comment by href** [comment]
😳

**Comment by href** [comment]
With the latest Python3 branch of Mitogen this now also works with Python 3. Now all we need to do is wait for Mitogen's PyPI release until we can release a Suitable that runs on Mitogen.

**Comment by dw** [comment]
There should be a stable release of Mitogen on PyPI by tomorrow evening -- just have to write the release notes :)  Sorry about the delay -- this turned out to be a nightmare target to hit, but we're there now!

**Comment by href** [comment]
Yay! Sorry for the headaches caused 😅

I'm currently on vacation. I'll push a new Suitable release with Mitogen support in August.

**Comment by href** [comment]
Mitogen support has been released on PyPI. To use the Mitogen Powered Ansible API™ simply install Mitogen alongside Suitable:

```bash
pip install suitable mitogen
```

Afterwards, use a slightly different import:
```python
from suitable.mitogen import Api
Api('localhost').command('whoami')
```

This is somewhat experimental at the moment, so consider yourself warned. Also, many thanks to @dw for all the great work on Mitogen 👍

**Comment by href** [comment]
This seems to be working so I'll close this. Possible errors should be added as new issues.
