### ISSUE TITLE
Debug verbosity doesn't appear to exist

### ISSUE THREAD

**Issue by VacuousCoder** [seantis/suitable#14]
Initiating the api with connection = Api(host, remote_user='root', verbosity='debug') only seems to log INFO. When installing packages with apt through suitable it simply tells me what is being run through an info log. Am I missing something or is the general consensus to just _debug_ your code if you want to see more info. 

Also, can the times be moved to the debug log? It seems like more of a debug log to me and detracts quite a bit from the readability of my logs. 

Thanks!

**Comment by href** [comment]
So far we only pass the verbosity down to Ansible. Personally I don't use it much as I intercept all module errors in my own code and log that in a custom way. But that of course doesn't include anything from the code that was called on Ansible's side.

I was under the impression that letting Ansible know what verbosity we want through its `Play` class would be enough, but I've just checked this and that only does little to increase the logging output.

To fix this I'll probably have to patch the [Display](https://github.com/ansible/ansible/blob/bbfe7a8b2f7ce5bf3fe87885e71436f45251f99c/lib/ansible/utils/display.py#L80) class which won't be particularly pretty. Ansible only uses global instance of this class during script execution and falls back to the default in other cases:

```python
try:
    from __main__ import display
except ImportError:
    from ansible.utils.display import Display
    display = Display()
```

Also, can you clarify what you mean by this:

> Also, can the times be moved to the debug log? It seems like more of a debug log to me and detracts quite a bit from the readability of my logs.

Do you mean that there should be a timestamp at the beginning of each line?

**Comment by VacuousCoder** [comment]
https://github.com/seantis/suitable/blob/master/suitable/module_runner.py#L136

**Comment by href** [comment]
All clear, I think that's a reasonable change.

**Comment by href** [comment]
I've changed the time taken log and changed the 'debug' verbosity to cause Ansible to output like it was called using `-vvvvvv`. I could also add an option to get anything between `-v`and `-vvvvvv`. 

But I had a look at some of the output and I'm not sure how useful that distinction would be.

Can you have a look at it and see if this works for you?

**Comment by href** [comment]
I pushed a new release with this change in it to PyPI. Feel free to reopen if this doesn't solve your issue.
