### ISSUE TITLE
localhost always asuming it's local connection

### ISSUE THREAD

**Issue by accountgit** [seantis/suitable#18]
Using ssh tunnels, you need to contact to localhost to conect to remove host.
Always in suitable it's assumed that the connection it's local.

Maybe one idea could be use ssh://localhost:XX in the server list?

**Comment by href** [comment]
Suitable defaults to a local connection as that's probably what you usually want. You can however override this behaviour by specifying the connection option:

```python
Api('localhost', connection='smart')
```

See the implementation for details: https://github.com/seantis/suitable/blob/05d9a2897d14f07c54ee04f50494665d7e7460dd/suitable/api.py#L136-L144

**Comment by href** [comment]
I assume this worked for you, if not feel free to reopen the ticket.
