### ISSUE TITLE
how to consume 3rd party ansible modules ?

### ISSUE THREAD

**Issue by Azulinho** [seantis/suitable#25]
I found this: https://github.com/seantis/suitable/issues/19#issuecomment-408863432

is there a better way ?
I have some ansible modules made by different github folks that are meant to be downloaded and dumped into the ansibles modules folder, however when using ansible, that ansibles modules folder is usually within a virtualenv python site-packages directory.
This works if I copy the module into that directory, but I'm keen to find a more pythonic clean way of consuming 3rd party ansible modules.

any ideas?

**Comment by href** [comment]
I'm not familiar with 3rd party modules for Ansible. I assume whatever works with Ansible would work with Suitable, unless there's some kind of setup/configuration that needs to be done that is not implemented by Suitable.

Can you give me an example of what you're trying to accomplish? The simpler, the better.

**Comment by Azulinho** [comment]
I should have tried this first, it works the same way as in 'normal' ansible,
https://docs.ansible.com/ansible/latest/dev_guide/developing_locally.html

just set your `ANSIBLE_LIBRARY` variable to a directory, and dump the custom ansible modules in there.

voila'
