### ISSUE TITLE
Server reconnect for each API call

### ISSUE THREAD

**Issue by href** [seantis/suitable#28]
I have a question, seems like below logic result in the API connect to remoter server for every file. Is it possible to run all those task without reconnect server?

```python

# I'v create api obj by below:
api = Api(self.target_server,
                  remote_user='my_ssh_user', 
                  remote_pass='my_ssh_passwd',
                  become="yes",
                  become_user="my_sudo_user",
                  ignore_errors=True,
                  ignore_unreachable=True,
                  verbosity='debug'
                  )

# then try to send some files to remote:
for file in filenamelists:
     api.copy(src=file, dest=/path/to/mydest/, mode=755)

# seems every file will cause the server reconnect for every single file.
```

_Originally posted by @don2ccc in https://github.com/seantis/suitable/issues/27#issuecomment-494293760_

**Comment by href** [comment]
I've split this up into a new issue as it seems unrelated to the original issue. I'll have a look at this when I have the time, but that might easily be a few days.

**Comment by don2ccc** [comment]
I'v did test from server side, actually there were only one ssh session connected during the API call in the for loop.

**Comment by href** [comment]
Oh so this can be closed?

Aside: If you're just looking for a speed-up you might be a able to leverage Mitogen successfully:
https://suitable.readthedocs.io/en/latest/#mitogen-support

Just be sure to use Ansible 2.7 in this case as 2.8 is not yet supported.

**Comment by don2ccc** [comment]
thank you.
please mark as close.
I m now using API with Mitogen.
