### ISSUE TITLE
Not possible to define host variables

### ISSUE THREAD

**Issue by jokurz** [seantis/suitable#36]
It would be great to be able to set host depended variables (e.g. to set `ansible_python_interpreter`, `ansible_host` or `ansible_ssh_common_args` per host).

I would propose to add a third possibility to define hosts in `suitable.Api(hosts)`:

1. As string (single host or list of hosts delimited by blank)
  Example: `"host1 host2:22"`
2. As list or set
  Example: `['host1', 'host2:22']`
3. As dict
  Example: 
```py
{
  'host1': {'ansible_host': 'host1.example.org'},
  'host2': {'var1': 'value'},
  'host3': {} # Allow None?
}
```

**Comment by href** [comment]
👍 - I think this could be useful for some use-cases and it wouldn't require any changes to existing code.

**Comment by href** [comment]
Though I would assume this might get tricky in the implementation. That is to say, I wouldn't be surprised if you run into some obstacles with hidden Ansible state, but you are very welcome to try :wink:
