### ISSUE TITLE
Bastion example

### ISSUE THREAD

**Issue by VacuousCoder** [seantis/suitable#42]
Hey, I'm trying to figure out how to use a jump host properly and was hoping for an example. The jump host and remote hosts use the same username and private key. 

I've tried a bunch of different variations of this

`ansible = Api(host, remote_user=username, become_user='root', private_key_file=sshkey, become='yes', ssh_common_args='-o StrictHostKeyChecking=no', ssh_extra_args='-o ProxyCommand="ssh -W %h:%p -q username@jumphost"')`

and the -F to use the config file to no avail. So, could you provide a working example please?

Thanks

**Comment by patrickbucher** [comment]
Any luck with the `-J` flag as described in [this article](https://www.redhat.com/sysadmin/ssh-proxy-bastion-proxyjump)?

**Comment by patrickbucher** [comment]
@VacuousCoder Have you been able to try out this approach?
