### ISSUE TITLE
Api dry_run=True causes shell() invocations to throw exception

### ISSUE THREAD

**Issue by elgow** [seantis/suitable#45]
This may not be fixable because dry_run would imply not executing a shell command that could have side-effects, but it is important to be aware that:

Executing `Api(host).shell('whoami')` on a linux system will return your user name on the target host in stdout. 

Executing `Api(host, dry_run=True).shell('whoami')` on a linux system will give you the following type of error

```
 File ".../deploy_to_clean_server.py", line 53, in configure_server
    admin_user_name = Api(host, dry_run=True).shell('whoami').stdout()  # get my user name on target host
  File ".../lib/python3.6/site-packages/suitable/runner_results.py", line 17, in <lambda>
    return lambda server=None: self.acquire(server, key)
  File ".../lib/python3.6/site-packages/suitable/runner_results.py", line 27, in acquire
    raise KeyError("{} could not be contacted".format(server))
KeyError: 'None could not be contacted'
```

**Comment by lowercase00** [comment]
@Daverball I think this is solved? Couldn't reproduce it locally:

```python
>>> ansible = Api(host, dry_run=True)
>>> ansible.shell("whoami")
{'contacted': {}, 'unreachable': {}}
```

**Comment by lowercase00** [comment]
@Daverball  I guess this is solved?
Couldn't reproduce it locally:

```python
>>> ansible = Api(host, dry_run=True)
>>> ansible.shell("whoami")
{'contacted': {}, 'unreachable': {}}
```

**Comment by Daverball** [comment]
@lowercase00 To reproduce it you will need to call `stdout()` on the result of shell. So it's more of an enhancement than a bug, since it should probably throw an exception either way, the exception should just be more helpful, to let you know that calling `.stdout()` on a dry run makes no sense.

Maybe it would also be fine to just make it work without errors and pre-fill it with empty output.

**Comment by lowercase00** [comment]
Oh, right, my apologies.
From what I understood so far, when we call `ansible.shell(...)` we are accessing Ansible's module directly (modules being dynamically loaded and hooked up through the runner, and the module has a bunch of internal methods (like `stdout()`)?
Well, I'll try to dig deeper to understand the logic... was trying to grab low hanging fruits around here, and this doesn't seem to be the case for this one...

**Comment by Daverball** [comment]
There is now a less confusing error message for this scenario, starting with 0.20.1
